//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedicamento
    {
        public int IIDCONSULTA { get; set; }
        public int IIDMEDICAMENTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
