//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int IIDDOCTOR { get; set; }
        public string NOMBRE { get; set; }
        public string APPATERNO { get; set; }
        public string APMATERNO { get; set; }
        public Nullable<int> IIDCLINICA { get; set; }
        public Nullable<int> IIDESPECIALIDAD { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONOCELULAR { get; set; }
        public Nullable<int> IIDSEXO { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public string NOMBREARCHIVO { get; set; }
        public string ARCHIVO { get; set; }
    
        public virtual Clinica Clinica { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
